"""Adds players.earned column

Revision ID: 85e5f3206b24
Revises: 
Create Date: 2023-09-04 13:37:41.040951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e5f3206b24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('earned', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_players_earned'), 'players', ['earned'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_earned'), table_name='players')
    op.drop_column('players', 'earned')
    # ### end Alembic commands ###
